load("//tools:ts.bzl", "myorg_ts_binary", "myorg_ts_library")

# Hand-written launcher. Gazelle attaches a generated private library.
myorg_ts_binary(
    name = "cli_bin",
    data = ["users.json"],
    entry_point = "main.ts",
    deps = [":cli_bin_lib"],
)

filegroup(
    name = "templates",
    srcs = glob(["*.template.ts"]),
)

myorg_ts_library(
    name = "cli",
    srcs = ["types.d.ts"],
    visibility = ["//visibility:public"],
)

myorg_ts_library(
    name = "cli_bin_lib",
    srcs = [
        "main.ts",
        "types.d.ts",
    ],
    tags = ["gazelle_ts_binary_library"],
    tsconfig_types = ["node"],
    visibility = ["//visibility:private"],
    deps = [
        "//:node_modules/@myrepo_generated/synthetic",
        "//:node_modules/@types/node",
        "//packages/core",
        "//packages/utils/math/deep",
        "//tools:mystery",
    ],
)
