syntax = "proto3";
package gazelle_ts.import_extractor;

message Request {
  uint32 id = 1;
  oneof data {
    TsQueryRequest ts_query = 2;
  }
}

message Response {
  uint32 id = 1;
  oneof data {
    TsResponseResult ts_result = 2;
    ResponseError error = 4;
  }
}

message ResponseError {
  string message = 1;
}

// --- TypeScript ---

message TsQueryRequest {
  repeated string files = 1;
}

message TsResponseResult {
  repeated TsImportByFile imports = 1;
}

message TsImportByFile {
  string file = 1;
  repeated string import_paths = 2;
  repeated string global_names = 3;
  bool has_main = 4;
}
